---
- hosts: development
  become: true
  become_user: root
  tasks:
   - debug: var=ansible_all_ipv4_addresses
     tags:
      - debug
   
   - name: Echo
     shell: echo {{ ansible_all_ipv4_addresses[0] }} > /var/tmp/hoge
     when: "'development' in group_names and ansible_os_family == 'RedHat'"
     become: false
     tags:
      - debug
   
   - debug: msg="{{ arg1 }}"
     tags:
      - debug

- hosts: development
  become: true
  become_user: root
  roles:
   - disable-selinux
   - {
       role: bennojoy.mysql, mysql_root_db_pass: "{{ mysql.root_pwd }}",
       mysql_db: [ {name: wordpress} ],
       mysql_users: [{name: user01, pass: "{{ mysql.user_pwd }}", priv: "*.*:ALL"}] 
     }
   - iocdn.httpd
   - iocdn.wordpress
   - elasticsearch
   - kibana
   - td-agent
  tasks:
   - name: Copy Test
     copy: src=./files/tmp/test.txt dest=/tmp/test.txt.check owner=root group=root mode=0644
     become: true
